### ISSUE TITLE
Compatibility with Internet Explorer

### ISSUE THREAD

**Issue by SH801** [tyleryasaka/semantic-ui-range#20]
Great slider!

However, I just tried it with Internet Explorer 11 on Windows 7 and it doesn't seem to work.

**Comment by tyleryasaka** [comment]
@SH801 Thanks for pointing this out!

Turns out javascript [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) are not supported by IE. I updated the code not to use them.

https://github.com/tyleryasaka/semantic-ui-range/commit/feed1910090a792a6c7a2769c29274625d2579f9

**Comment by SH801** [comment]
Absolutely fantastically quick turnaround. Thank you!
